注意：请在以下单元格中填写您的信息后再运行该程序！

In [ ]:
# 请填写您的用户名和密码
USER_ID = "10001"
USER_PASSWORD = "00000"
# 请填写您的域名地址
BASE_DOMAIN = "http://star-eyes.cloud"

In [ ]:
!pip install deeplabcut

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
#引入deeplabcut环境并创建DLC项目

%reload_ext numpy
%reload_ext matplotlib
%reload_ext mpl_toolkits
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
PATH = "/content/drive/MyDrive/DLC"
CONF_PATH = "/content/drive/MyDrive/DLC/config.yaml"

try:
  os.mkdir("working_dir")
except FileExistsError:
  pass

# !touch ./working_dir/temp.mp4
import deeplabcut


# video_path = "/content/working_dir/temp.mp4"
# videotype = os.path.splitext(video_path)[-1].lstrip('.')




# path_config_file = deeplabcut.create_pretrained_project(
#   project_name,
#   your_name,
#   [video_path],
#   videotype=videotype,
#   model=model2use,
#   analyzevideo=False,
#   createlabeledvideo=False,
#   copy_videos=True, #must leave copy_videos=True
# )
# os.remove("./working_dir/temp.mp4")
#安装完成后必须通过下列命令重启运行时


# os._exit(0)

In [ ]:
# 从文件夹中读取视频文件名，挑选当前分钟的视频文件，将视频文件送入DEEPLABCUT进行处理
!pip install wget
!pip install shed
!pip install bs4
import re
import os
import datetime
import pytz
import wget
import requests
import shed
from bs4 import BeautifulSoup
beijing = pytz.timezone("Asia/Shanghai")
working_dir = "/content/working_dir/"
csv_dir = "/content/csv_dir/"
def process_main():
  try:
    os.mkdir("/content/working_dir")
  except FileExistsError:
    pass

  try:
    os.mkdir("/content/csv_dir")
  except FileExistsError:
    !rm -rf /content/csv_dir/*
  # working_dir = "E:\\process working dir\\"
  

  
  now = datetime.datetime.now(beijing) - timedelta(minutes=4)  #考虑到时间上传延迟，获取三分钟前的时间
  nowstr = now.strftime('%Y%m%d_%H%M')
  nowstr = nowstr + ".mp4"
  regex = r"\D{0}" + nowstr + r"\D{0}"
  print(regex)

  # TODO:使用list建立已处理文件表，未处理的文件则送入filtered_links list中
  # 从nginx中读取文件列表，存入links中
  url = BASE_DOMAIN + "/vstream/" # assuming this is the nginx file server address
  response = requests.get(url)
  soup = BeautifulSoup(response.text, "html.parser")
  links = soup.find_all("a") # find all links in the HTML page
  

  #将links从resultset类型转化为list类型
  links = list(links)
  print(links)
  print(type(links))
  links = [str(link) for link in links]
  # 过滤文件列表
  filtered_links = list(filter(lambda x: re.findall(regex, x), links))
  
  pattern = r"<[^>]*>"
  for i in range(len(filtered_links)) :
    filtered_links[i] = url + re.sub(pattern, "", filtered_links[i])
  print(filtered_links)
  if(len(filtered_links) == 0):
    print("Do not find any videos that should be processed at nginx server. This program will do nothing this minute.")
    return 0;
  # 批量下载
  !rm -rf //content/working_dir/*
  for filtered_link in filtered_links:
    print("Downloading file: " + filtered_link)
    wget.download(filtered_link,out=working_dir)

  # 调用DLC处理
  filtered_files = os.listdir(working_dir)
  for filtered_file in filtered_files:
    print("Processing file: " + filtered_file)
    filtered_file = "/content/working_dir/" + filtered_file
    dlc_process(filtered_file)



  #清空工作文件夹(在每次处理循环最后)
  # for file in os.listdir(working_dir):
  #   os.remove(working_dir + file)
  # 清空working_dir
  !rm -rf /content/working_dir/*



Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!nvidia-smi

Fri Apr 14 15:27:12 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   58C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
def dlc_process(video_path):
  video_path = deeplabcut.DownSampleVideo(video_path, width=300)
  print(video_path)
  deeplabcut.analyze_videos(CONF_PATH,[video_path],gputouse=0,save_as_csv=True,destfolder=csv_dir)
  # 调用LSTM分析生成的csv文件
  csv_list = os.listdir(csv_dir)
  # 筛选以.csv结尾的文件
  csv_list = [s for s in csv_list if s.endswith(".csv")]
  # 将csv转交给LSTM
  for csv_file in csv_list:
    csv_file_fullpath = csv_dir + csv_file
    print(csv_file_fullpath)
    LSTM_Predict(csv_file_fullpath)
    !rm -rf ${csv_file_fullpath}    #在处理完后清理该文件




In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd
from tensorflow import keras
from tensorflow.keras import layers
import datetime
from sklearn.preprocessing import MinMaxScaler
#mydata[['x1','x2','x3']] = MinMaxScaler().fit_transform(mydata[['x1','x2','x3']])


FRAME_NUMBER = 72
def LSTM_Predict(csv_file_fullpath):
  print("predicting:")
  print(csv_file_fullpath)
  #读入csv至numpy
  pd_tmp = pd.read_csv(csv_file_fullpath,header=1,usecols=lambda x:x!="bodyparts")
  pd_tmp = pd_tmp.drop(index = 0)
  pd_tmp = pd_tmp.astype(float)
  numpy_origin = pd_tmp.to_numpy()
  # numpy_origin = np.loadtxt(csv_file_fullpath,delimiter=",")
  print(numpy_origin)
  print(numpy_origin.shape)
 
  #切割900帧（一分钟）的numpy array,LSTM一次处理72帧
  CUT_NUM = int(numpy_origin.shape[0] - numpy_origin.shape[0] % 72) / 72
  # numpy_origin = np.pad(numpy_origin, ((0, pad_rows), (0, 0)), 'constant')
  numpy_origin = np.delete(numpy_origin,range(int(CUT_NUM*72),numpy_origin.shape[0]),axis=0)
  numpy_aftercut = numpy_origin.reshape(int(CUT_NUM),72, 60)
  # numpy_aftercut = numpy_aftercut[:,:,:-1]
  print("after cut:")
  print(numpy_aftercut)
  print(numpy_aftercut.shape)
  for i in range (numpy_aftercut.shape[0]):
    numpy_iter =  numpy_aftercut[i,:,:]
    if (likelihood_check(numpy_iter)==True):
      print("have animal, analyzing with LSTM")
      LSTM_classification(numpy_iter,csv_file_fullpath)
    else :
      print("no animal")
  


#判断csv中有无动物；若有动物则调用model predict,若无直接退出，不写入数据库，likelihood阈值设为0.07
def likelihood_check(numpy_given):
  likelihood_sub_numpy = numpy_given[:,2::3]
  print("Likelihood numpy:")
  print(likelihood_sub_numpy)
  print(likelihood_sub_numpy.dtype)
  average = np.mean(likelihood_sub_numpy)
  print(average)
  if(average<0.07):
    print("There is no animal in this piece of video.")
    return False
  return True

def LSTM_classification(numpy_iter,csv_file_fullpath):
  #x,y坐标处理 & 归一化数据
  scaler = MinMaxScaler()
  flag = True;
  for j in range(72):
    x_cor_tmp = numpy_iter[j][::3]
    y_cor_tmp = numpy_iter[j][1::3]
    x_cor_tmp = scaler.fit_transform(x_cor_tmp.reshape(-1,1))
    y_cor_tmp = scaler.fit_transform(y_cor_tmp.reshape(-1,1))
    if(flag): #create a new np array
      flag = False;
      np_after_scaled =np.concatenate([x_cor_tmp.flatten(),y_cor_tmp.flatten()],axis = 0)
    else: 
      np_after_scaled = np.vstack([np_after_scaled,np.concatenate([x_cor_tmp.flatten(),y_cor_tmp.flatten()],axis = 0)])
  np_after_scaled = np_after_scaled.reshape(1,72,40)
  print(np_after_scaled.shape)

  #加载LSTM模型
  LSTM_model = tf.keras.models.load_model("/content/drive/MyDrive/LSTM_model")
  model_output = LSTM_model.predict(np_after_scaled)
  print(model_output)

  #模型输出：0/eating 2/jumping 3/walking
  print(model_output[0][0])
  # 设定事件类型
  if(max(model_output[0])<0.6):
    event_type = "发现动物出现"
  elif(model_output[0][0]<max(model_output[0][1],model_output[0][2])):
    event_type = "发现动物正在进食"
  elif(model_output[0][1]<max(model_output[0][2],model_output[0][0])):
    event_type = "发现动物正在跳跃"
  else:
    event_type = "发现动物正在移动"
  
  # 设定事件发生时间
  event_time = datetime.datetime.now(beijing) - datetime.timedelta(minutes=4)
  event_time = event_time.strftime("%Y-%m-%d %H:%M")
  cam_id = re.split("_",csv_file_fullpath)
  print(cam_id)
  cam_id = re.split("/",cam_id[0])
  cam_id_final = cam_id[-1]
  print(type(cam_id_final))
  print(cam_id_final)
  print(event_time)
  print(event_type)
  event_class = Event(cam_id=cam_id_final,time =event_time,event_type = event_type)
  update_sql(event_class)
  



In [ ]:
# 事件class
class Event:
  cam_id = "00000"
  time = ""
  event_type = "default"
  def __init__(self,cam_id,time,event_type):
    self.cam_id = cam_id
    self.time = time
    self.event_type = event_type

  def print_self():
    print(cam_id)
    print(time)
    print(event_type)


In [ ]:
def update_sql(event_to_update):
  API_URL = "http://star-eyes.cloud:9090/api/event/addEvent/"
  headers = {'Content-Type': 'application/json'}
  print(API_URL)
  print(USER_ID)
  data = {"user_id":USER_ID,"password":USER_PASSWORD,"cam_id":event_to_update.cam_id,"time":event_to_update.time,"event_type":event_to_update.event_type}
  print(data)
  response = requests.post(url=API_URL, headers=headers,data = data)
  print(response.status_code)
  print(response.text)


In [ ]:
#设定定时器，每隔一分钟执行一次main_process()
import sched
import time
from datetime import timedelta

s = sched.scheduler(time.time, time.sleep)

def run():
  process_main() # 执行函数
  s.enter(60, 1, run) # 每隔 60 秒执行一次函数

s.enter(0, 1, run) # 第一次执行
s.run() # 启动调度器

\D{0}20230321_1900.mp4\D{0}
[<a href="../">../</a>, <a href="61206_20230321_1617.mp4">61206_20230321_1617.mp4</a>, <a href="61206_20230321_1856.mp4">61206_20230321_1856.mp4</a>, <a href="61206_20230321_1857.mp4">61206_20230321_1857.mp4</a>, <a href="61206_20230321_1858.mp4">61206_20230321_1858.mp4</a>, <a href="61206_20230321_1900.mp4">61206_20230321_1900.mp4</a>]
<class 'list'>
['http://star-eyes.cloud/vstream/61206_20230321_1900.mp4']
Processing file: 61206_20230321_1900.mp4
/content/working_dir/61206_20230321_1900downsampled.mp4
Using snapshot-75000 for model /content/drive/MyDrive/DLC/dlc-models/iteration-0/myDLC_modelZooJun3-trainset95shuffle1


/usr/local/lib/python3.9/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '


Starting to analyze %  /content/working_dir/61206_20230321_1900downsampled.mp4
Loading  /content/working_dir/61206_20230321_1900downsampled.mp4
Duration of video [s]:  60.07 , recorded with  15.0 fps!
Overall # of frames:  901  found with (before cropping) frame dimensions:  300 200
Starting to extract posture


100%|██████████| 901/901 [00:09<00:00, 92.93it/s] 


Saving results in /content/csv_dir/...
Saving csv poses!
The videos are analyzed. Now your research can truly start! 
 You can create labeled videos with 'create_labeled_video'
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.
/content/csv_dir/61206_20230321_1900downsampledDLC_resnet50_myDLC_modelZooJun3shuffle1_75000.csv
predicting:
/content/csv_dir/61206_20230321_1900downsampledDLC_resnet50_myDLC_modelZooJun3shuffle1_75000.csv
[[ 1.86138611e+02  1.90768661e+02  9.28278327e-01 ...  8.52198486e+01
   3.67050400e+01  2.38369089e-02]
 [ 1.79666229e+02  1.88532883e+02  8.37442577e-01 ...  8.16416473e+01
   4.46908455e+01  6.11048453e-02]
 [ 1.71278275e+02  1.75642868e+02  9.86436665e-01 ...  8.26839523e+01
   4.03038864e+01  3.36977802e-02]
 ...
 [ 1.30266251e+02  1.65141663e+02  6.59518316e-03 ...  1.92057037e+02
   7.44499969e+01  3.67558748e-02]
 [ 1

/usr/local/lib/python3.9/dist-packages/keras/engine/training_v1.py:2357: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,


[[2.7169049e-04 1.5615098e-02 9.8411328e-01]]
0.0002716905
['/content/csv', 'dir/61206', '20230321', '1900downsampledDLC', 'resnet50', 'myDLC', 'modelZooJun3shuffle1', '75000.csv']
<class 'str'>
csv
2023-03-21 19:08
发现动物正在进食
http://star-eyes.cloud:9090/api/event/addEvent/
10001
{'user_id': '10001', 'password': '00000', 'cam_id': 'csv', 'time': '2023-03-21 19:08', 'event_type': '发现动物正在进食'}
400
{"timestamp":"2023-03-21T11:12:41.110+00:00","status":400,"error":"Bad Request","path":"/api/event/addEvent/"}
Likelihood numpy:
[[0.00465212 0.00175789 0.00254175 ... 0.12708747 0.33534783 0.45147371]
 [0.00151493 0.00093894 0.00093591 ... 0.63718045 0.24090323 0.70841366]
 [0.00256141 0.00302873 0.00381787 ... 0.28100088 0.26934257 0.69501221]
 ...
 [0.82400447 0.22711685 0.44127512 ... 0.74645078 0.03997279 0.15170169]
 [0.00603807 0.00252739 0.00447546 ... 0.37758672 0.01996492 0.15104826]
 [0.01137588 0.00431532 0.01193856 ... 0.16182415 0.06019532 0.06244932]]
float64
0.10359540999323953
hav

/usr/local/lib/python3.9/dist-packages/keras/engine/training_v1.py:2357: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,


[[8.1961202e-03 2.3975618e-04 9.9156415e-01]]
0.00819612
['/content/csv', 'dir/61206', '20230321', '1900downsampledDLC', 'resnet50', 'myDLC', 'modelZooJun3shuffle1', '75000.csv']
<class 'str'>
csv
2023-03-21 19:08
发现动物正在进食
http://star-eyes.cloud:9090/api/event/addEvent/
10001
{'user_id': '10001', 'password': '00000', 'cam_id': 'csv', 'time': '2023-03-21 19:08', 'event_type': '发现动物正在进食'}
400
{"timestamp":"2023-03-21T11:12:46.092+00:00","status":400,"error":"Bad Request","path":"/api/event/addEvent/"}
Likelihood numpy:
[[0.0245818  0.00514184 0.01437773 ... 0.12970312 0.08041249 0.10057553]
 [0.04550966 0.01734325 0.02158912 ... 0.50484776 0.06202491 0.28601676]
 [0.05786217 0.0376297  0.03357282 ... 0.12881052 0.02942289 0.18441407]
 ...
 [0.90564817 0.91461205 0.91155958 ... 0.17207091 0.30646542 0.22893389]
 [0.91903633 0.97501481 0.89488155 ... 0.06326027 0.21081509 0.14653987]
 [0.88673931 0.97156197 0.89852047 ... 0.05293963 0.24901837 0.09925652]]
float64
0.4926493620976948
have a

/usr/local/lib/python3.9/dist-packages/keras/engine/training_v1.py:2357: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,


[[1.2148468e-04 6.3472561e-04 9.9924386e-01]]
0.00012148468
['/content/csv', 'dir/61206', '20230321', '1900downsampledDLC', 'resnet50', 'myDLC', 'modelZooJun3shuffle1', '75000.csv']
<class 'str'>
csv
2023-03-21 19:08
发现动物正在进食
http://star-eyes.cloud:9090/api/event/addEvent/
10001
{'user_id': '10001', 'password': '00000', 'cam_id': 'csv', 'time': '2023-03-21 19:08', 'event_type': '发现动物正在进食'}
400
{"timestamp":"2023-03-21T11:12:50.747+00:00","status":400,"error":"Bad Request","path":"/api/event/addEvent/"}
Likelihood numpy:
[[0.92087102 0.95130557 0.96721148 ... 0.08963288 0.40048283 0.12047078]
 [0.93069631 0.95664495 0.97665364 ... 0.10700831 0.34449789 0.04008775]
 [0.96706319 0.95552367 0.97099775 ... 0.09523761 0.69287884 0.10440186]
 ...
 [0.94170368 0.88739324 0.92413276 ... 0.04204835 0.08314282 0.02561261]
 [0.88267505 0.56759071 0.83712083 ... 0.13650805 0.32205954 0.07527006]
 [0.92094964 0.65133911 0.90883833 ... 0.14840186 0.26564053 0.07130021]]
float64
0.7127969322273404
hav

/usr/local/lib/python3.9/dist-packages/keras/engine/training_v1.py:2357: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,


[[4.3610309e-04 6.3113393e-03 9.9325258e-01]]
0.0004361031
['/content/csv', 'dir/61206', '20230321', '1900downsampledDLC', 'resnet50', 'myDLC', 'modelZooJun3shuffle1', '75000.csv']
<class 'str'>
csv
2023-03-21 19:08
发现动物正在进食
http://star-eyes.cloud:9090/api/event/addEvent/
10001
{'user_id': '10001', 'password': '00000', 'cam_id': 'csv', 'time': '2023-03-21 19:08', 'event_type': '发现动物正在进食'}
400
{"timestamp":"2023-03-21T11:12:55.649+00:00","status":400,"error":"Bad Request","path":"/api/event/addEvent/"}
Likelihood numpy:
[[0.97729141 0.90643829 0.90024579 ... 0.04768756 0.1790233  0.0282105 ]
 [0.9647159  0.91309547 0.89475405 ... 0.14794825 0.47091234 0.11904711]
 [0.96605742 0.9341253  0.95396388 ... 0.2736662  0.65124071 0.25409979]
 ...
 [0.96962959 0.94789177 0.9529689  ... 0.0874465  0.17911649 0.02206853]
 [0.9287113  0.91568601 0.89893162 ... 0.04281008 0.04107167 0.04199943]
 [0.90302801 0.92231417 0.79829723 ... 0.11292051 0.02269903 0.0263743 ]]
float64
0.647415868830285
have 

/usr/local/lib/python3.9/dist-packages/keras/engine/training_v1.py:2357: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,


[[0.00279752 0.00316271 0.9940398 ]]
0.002797517
['/content/csv', 'dir/61206', '20230321', '1900downsampledDLC', 'resnet50', 'myDLC', 'modelZooJun3shuffle1', '75000.csv']
<class 'str'>
csv
2023-03-21 19:09
发现动物正在进食
http://star-eyes.cloud:9090/api/event/addEvent/
10001
{'user_id': '10001', 'password': '00000', 'cam_id': 'csv', 'time': '2023-03-21 19:09', 'event_type': '发现动物正在进食'}
400
{"timestamp":"2023-03-21T11:13:01.813+00:00","status":400,"error":"Bad Request","path":"/api/event/addEvent/"}
Likelihood numpy:
[[0.93839544 0.93738139 0.83674157 ... 0.05241656 0.06922466 0.02459643]
 [0.88699329 0.71643817 0.5305739  ... 0.13223463 0.02155183 0.02830279]
 [0.97818053 0.95790839 0.81574351 ... 0.02979445 0.11456358 0.01982887]
 ...
 [0.04322735 0.03313252 0.0480529  ... 0.00613641 0.00702516 0.03086747]
 [0.46486902 0.02280395 0.0419781  ... 0.00572788 0.00703692 0.08585579]
 [0.91916555 0.70414966 0.26914099 ... 0.00882394 0.01080194 0.03543461]]
float64
0.3118445156604745
have animal, a

/usr/local/lib/python3.9/dist-packages/keras/engine/training_v1.py:2357: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,


[[7.3387763e-03 1.1202384e-04 9.9254918e-01]]
0.0073387763
['/content/csv', 'dir/61206', '20230321', '1900downsampledDLC', 'resnet50', 'myDLC', 'modelZooJun3shuffle1', '75000.csv']
<class 'str'>
csv
2023-03-21 19:09
发现动物正在进食
http://star-eyes.cloud:9090/api/event/addEvent/
10001
{'user_id': '10001', 'password': '00000', 'cam_id': 'csv', 'time': '2023-03-21 19:09', 'event_type': '发现动物正在进食'}
400
{"timestamp":"2023-03-21T11:13:07.242+00:00","status":400,"error":"Bad Request","path":"/api/event/addEvent/"}
Likelihood numpy:
[[9.23304379e-01 7.61592805e-01 9.88532543e-01 ... 5.70962531e-03
  1.34622771e-02 3.41531821e-02]
 [9.75903153e-01 7.63396561e-01 9.86633539e-01 ... 1.01586999e-02
  1.59377940e-02 1.21531732e-01]
 [9.71455872e-01 1.41816780e-01 8.98036480e-01 ... 9.72677115e-03
  4.19471301e-02 1.30557911e-02]
 ...
 [1.72247377e-03 9.83581413e-04 4.82453121e-04 ... 1.47301242e-01
  6.25636056e-02 6.03177585e-02]
 [1.73072964e-02 2.38301698e-03 9.22716339e-04 ... 3.65961909e-01
  4.5434

/usr/local/lib/python3.9/dist-packages/keras/engine/training_v1.py:2357: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,


[[0.00219338 0.5552871  0.44251955]]
0.0021933846
['/content/csv', 'dir/61206', '20230321', '1900downsampledDLC', 'resnet50', 'myDLC', 'modelZooJun3shuffle1', '75000.csv']
<class 'str'>
csv
2023-03-21 19:09
发现动物出现
http://star-eyes.cloud:9090/api/event/addEvent/
10001
{'user_id': '10001', 'password': '00000', 'cam_id': 'csv', 'time': '2023-03-21 19:09', 'event_type': '发现动物出现'}
400
{"timestamp":"2023-03-21T11:13:13.779+00:00","status":400,"error":"Bad Request","path":"/api/event/addEvent/"}
Likelihood numpy:
[[1.61002472e-03 9.32541792e-04 1.15192728e-03 ... 4.22645032e-01
  3.09892625e-01 6.66220427e-01]
 [1.55083230e-03 7.84783391e-04 1.32901431e-03 ... 2.41298467e-01
  3.49181056e-01 8.08992863e-01]
 [2.16024672e-03 1.83784263e-03 2.83374358e-03 ... 4.72791642e-02
  1.89660504e-01 5.63939214e-01]
 ...
 [1.67587865e-02 3.06785293e-03 1.75057258e-02 ... 3.02668482e-01
  2.19891071e-02 1.26072720e-01]
 [1.71022546e-02 2.27098074e-03 1.84445805e-03 ... 3.14968564e-02
  3.50074172e-02 4.37

/usr/local/lib/python3.9/dist-packages/keras/engine/training_v1.py:2357: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,


[[4.0427770e-02 5.7182781e-04 9.5900047e-01]]
0.04042777
['/content/csv', 'dir/61206', '20230321', '1900downsampledDLC', 'resnet50', 'myDLC', 'modelZooJun3shuffle1', '75000.csv']
<class 'str'>
csv
2023-03-21 19:09
发现动物正在进食
http://star-eyes.cloud:9090/api/event/addEvent/
10001
{'user_id': '10001', 'password': '00000', 'cam_id': 'csv', 'time': '2023-03-21 19:09', 'event_type': '发现动物正在进食'}
400
{"timestamp":"2023-03-21T11:13:21.341+00:00","status":400,"error":"Bad Request","path":"/api/event/addEvent/"}
Likelihood numpy:
[[0.09795447 0.04630946 0.03655308 ... 0.53877455 0.07222001 0.30084157]
 [0.12870617 0.05650067 0.03129263 ... 0.37603563 0.05950791 0.23895893]
 [0.33849365 0.07053655 0.20973802 ... 0.58949602 0.04446712 0.31194365]
 ...
 [0.93497795 0.98610526 0.93444675 ... 0.0346513  0.10148519 0.07183959]
 [0.93407184 0.97487634 0.93517232 ... 0.0534007  0.16102354 0.06615833]
 [0.8719604  0.94963002 0.96570724 ... 0.03660903 0.23989418 0.03775371]]
float64
0.49466725198839817
have 

/usr/local/lib/python3.9/dist-packages/keras/engine/training_v1.py:2357: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,


[[9.0944573e-05 4.7589856e-04 9.9943310e-01]]
9.094457e-05
['/content/csv', 'dir/61206', '20230321', '1900downsampledDLC', 'resnet50', 'myDLC', 'modelZooJun3shuffle1', '75000.csv']
<class 'str'>
csv
2023-03-21 19:09
发现动物正在进食
http://star-eyes.cloud:9090/api/event/addEvent/
10001
{'user_id': '10001', 'password': '00000', 'cam_id': 'csv', 'time': '2023-03-21 19:09', 'event_type': '发现动物正在进食'}
400
{"timestamp":"2023-03-21T11:13:27.820+00:00","status":400,"error":"Bad Request","path":"/api/event/addEvent/"}
Likelihood numpy:
[[0.93165874 0.954799   0.9843629  ... 0.09770131 0.48407683 0.05638078]
 [0.95290452 0.94424325 0.96442676 ... 0.05564331 0.59929323 0.0483848 ]
 [0.96629357 0.97592586 0.97028536 ... 0.08449012 0.55804682 0.11546167]
 ...
 [0.87465274 0.90886307 0.87974787 ... 0.04573467 0.1356058  0.0198093 ]
 [0.95594156 0.85769606 0.94935477 ... 0.16052239 0.27900216 0.07090989]
 [0.96336472 0.90216041 0.79969251 ... 0.09031802 0.53892291 0.0361146 ]]
float64
0.7110871983899011
have

/usr/local/lib/python3.9/dist-packages/keras/engine/training_v1.py:2357: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,


[[6.8644102e-04 7.4724387e-03 9.9184108e-01]]
0.000686441
['/content/csv', 'dir/61206', '20230321', '1900downsampledDLC', 'resnet50', 'myDLC', 'modelZooJun3shuffle1', '75000.csv']
<class 'str'>
csv
2023-03-21 19:09
发现动物正在进食
http://star-eyes.cloud:9090/api/event/addEvent/
10001
{'user_id': '10001', 'password': '00000', 'cam_id': 'csv', 'time': '2023-03-21 19:09', 'event_type': '发现动物正在进食'}
400
{"timestamp":"2023-03-21T11:13:36.699+00:00","status":400,"error":"Bad Request","path":"/api/event/addEvent/"}
Likelihood numpy:
[[0.97177583 0.89304268 0.9152109  ... 0.13860148 0.28022137 0.06777592]
 [0.952694   0.94242764 0.9300577  ... 0.32480252 0.57505041 0.22150618]
 [0.96636045 0.94745648 0.82290608 ... 0.46102929 0.67797238 0.22093241]
 ...
 [0.96560526 0.88874471 0.93462646 ... 0.0647718  0.11467554 0.03144299]
 [0.97169244 0.92631787 0.92992324 ... 0.2921069  0.03308275 0.02869714]
 [0.93497127 0.93122327 0.86040825 ... 0.05761157 0.02089711 0.00887123]]
float64
0.6471699066117355
have 

/usr/local/lib/python3.9/dist-packages/keras/engine/training_v1.py:2357: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,


[[0.00163567 0.0021358  0.9962286 ]]
0.0016356744
['/content/csv', 'dir/61206', '20230321', '1900downsampledDLC', 'resnet50', 'myDLC', 'modelZooJun3shuffle1', '75000.csv']
<class 'str'>
csv
2023-03-21 19:09
发现动物正在进食
http://star-eyes.cloud:9090/api/event/addEvent/
10001
{'user_id': '10001', 'password': '00000', 'cam_id': 'csv', 'time': '2023-03-21 19:09', 'event_type': '发现动物正在进食'}
400
{"timestamp":"2023-03-21T11:13:45.389+00:00","status":400,"error":"Bad Request","path":"/api/event/addEvent/"}
Likelihood numpy:
[[0.88897264 0.84332097 0.69985038 ... 0.03495375 0.01400063 0.01025559]
 [0.97800702 0.96841383 0.94865918 ... 0.02672198 0.05210698 0.01275883]
 [0.97741276 0.9918555  0.98724771 ... 0.03655219 0.3330946  0.01235777]
 ...
 [0.96570623 0.85842896 0.4792276  ... 0.01104655 0.00699919 0.0228857 ]
 [0.94779634 0.44064665 0.96879554 ... 0.01430755 0.00715481 0.04993565]
 [0.85904133 0.13913403 0.90558845 ... 0.01966079 0.0257945  0.09410346]]
float64
0.319371535574141
have animal, a

/usr/local/lib/python3.9/dist-packages/keras/engine/training_v1.py:2357: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,


[[0.06562587 0.00261041 0.9317637 ]]
0.06562587
['/content/csv', 'dir/61206', '20230321', '1900downsampledDLC', 'resnet50', 'myDLC', 'modelZooJun3shuffle1', '75000.csv']
<class 'str'>
csv
2023-03-21 19:09
发现动物正在进食
http://star-eyes.cloud:9090/api/event/addEvent/
10001
{'user_id': '10001', 'password': '00000', 'cam_id': 'csv', 'time': '2023-03-21 19:09', 'event_type': '发现动物正在进食'}
400
{"timestamp":"2023-03-21T11:13:54.308+00:00","status":400,"error":"Bad Request","path":"/api/event/addEvent/"}
\D{0}20230321_1910.mp4\D{0}
[<a href="../">../</a>, <a href="61206_20230321_1856.mp4">61206_20230321_1856.mp4</a>, <a href="61206_20230321_1857.mp4">61206_20230321_1857.mp4</a>, <a href="61206_20230321_1858.mp4">61206_20230321_1858.mp4</a>, <a href="61206_20230321_1900.mp4">61206_20230321_1900.mp4</a>, <a href="61206_20230321_1901.mp4">61206_20230321_1901.mp4</a>]
<class 'list'>
[]
Do not find any videos that should be processed at nginx server. This program will do nothing this minute.
\D{0}2023032